runners:
  - description: parasite-runner-1
    options:
      url: 'https://www.mrdevops-gitlab.com/'
      registration_token: 'TxhtyPA3anBcDBDZV5Lw'
      tag_list: [ 'parasite', 'docker', 'python' ]
      executor: 'docker'
      docker_image: 'alpine:latest'
      retries: 1
  - description: parasite-runner-2
    options:
      url: 'https://www.mrdevops-gitlab.com/'
      registration_token: 'TxhtyPA3anBcDBDZV5Lw'
      tag_list: [ 'parasite', 'docker', 'python' ]
      executor: 'docker'
      docker_image: 'alpine:latest'
      retries: 1

